title: Philipp Mondorf
logo:  # you can add own logo.
description: Reasoning in LLMs and humans
baseurl: ""
url: https://PMMon.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Philipp Mondorf
  image: '/assets/img/about.jpg'
  job: Exploring the Frontiers of Intelligence
  bio: |+
    <br />
    Hi! I'm a second-year Ph.D. student at the <a href="https://mainlp.github.io/">Munich AI & NLP Research Lab (MaiNLP)</a> at 
    <a href="https://www.lmu.de/en/">Ludwig-Maximilians-University</a>, under the supervision of <a href="https://bplank.github.io/">Prof. Dr. Barbara Plank</a>.
    <br />
    <br />
    My research focuses on reasoning in large language models.
    Through extensive <a href="https://pmmon.github.io/publications/">evaluations</a> of both the output behavior and internal processes of current LLMs in reasoning scenarios, my work seeks to enhance our understanding of reasoning in LLMs.
    <br />
    <br />
    Before pursuing my Ph.D., I gained experience in industry working as an AI engineer (<a href="https://pmmon.github.io/cv/">CV</a>). 
    Furthermore, I hold a Master's degree in Systems, Control, and Robotics obtained from the <a href="https://www.kth.se/en">Royal Institute of Technology (KTH)</a> in Stockholm, and a Bachelor's degree in Engineering Science from the <a href="https://www.tum.de/en">Technical University of Munich (TUM)</a>.
    <br />
    <br />
    If you have questions or are interested in collaborating on research projects, please feel free to contact me!
    <br />
  email: P.Mondorf@lmu.de
  google_scholar: https://scholar.google.de/citations?user=lu0EbWYAAAAJ&hl=de&authuser=1
  github: https://github.com/PMMon
  last_update:  October 2023
  linkedin: https://www.linkedin.com/in/philipp-mondorf-b733bb221/
  twitter: https://twitter.com/PMMondorf



# Contact links
# TODO: Potentially add later.
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#

# Comment Section (Disqus)
disqus-identifier: PM-personal # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics:
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
